export const LOGIN_START = "LOGIN_START"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"

export const LOGOUT = "LOGOUT"

export const REGISTER_START = "REGISTER_START"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"


export const GOOGLE_START = "GOOGLE_START"
export const GOOGLE_FAIL = "GOOGLE_FAIL"
export const GOOGLE_SUCCESS = "GOOGLE_SUCCESS"


export const FORGOT_PASSWORD_START = "FORGOT_PASSWORD_START"
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL"
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS"


export const RESET_START = "RESET_START"
export const RESET_FAIL = "RESET_FAIL"
export const RESET_SUCCESS = "RESET_SUCCESS"

export const AUTO_AUTHENTICATE = "AUTO_AUTHENTICATE"