export const QUESTION_FETCH_START = "QUESTION_FETCH_START";
export const QUESTION_FETCH_FAIL = "QUESTION_FETCH_FAIL";
export const QUESTION_FETCH_SUCCESS = "QUESTION_FETCH_SUCCESS";
export const QUERY_CHANGE = "QUERY_CHANGE";

export const PAGE_CHANGE = "PAGE_CHANGE";
